era: "UL2017"
isMC: false
luminosity: 41.48
threads: 30

# configuration for ResolvedAnalysis.cpp
############################################################################################################
ntuple_path:
  - "/data3/ggNtuples/V10_06_30_01/job_SingleEle_Run2017B_UL/*.root"
  - "/data3/ggNtuples/V10_06_30_01/job_SingleEle_Run2017C_UL/*.root"
  - "/data3/ggNtuples/V10_06_30_01/job_SingleEle_Run2017D_UL/*.root"
  # - "/data3/ggNtuples/V10_06_30_01/job_SingleEle_Run2017E_UL/*.root"
  # - "/data3/ggNtuples/V10_06_30_01/job_SingleEle_Run2017F_UL/*.root"

# skimTree_path:
  # - "/data4/chenghan/electron/skimTree/20230214/job_DoubleEG_Run2017B_UL.root"
  # - "/data4/chenghan/electron/skimTree/20230214/job_DoubleEG_Run2017C_UL.root"
  # - "/data4/chenghan/electron/skimTree/20230214/job_DoubleEG_Run2017D_UL.root"
  # - "/data4/chenghan/electron/skimTree/20230214/job_DoubleEG_Run2017E_UL.root"
  # - "/data4/chenghan/electron/skimTree/20230214/job_DoubleEG_Run2017F_UL.root"

miniTree_path:
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017B_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017C_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017D_UL2017.root"
  # - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017E_UL2017.root"
  # - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017F_UL2017.root"

external_files:
  # mergedID_model: # XGBReader (xgboost/c_api.h)
  #   M2EB: "/data4/chenghan/external/MergedID/Output_Merged2GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EB/XGB/XGB_modelXGB.txt"
  #   M2EE: "/data4/chenghan/external/MergedID/Output_Merged2GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EE/XGB/XGB_modelXGB.txt"
  #   M1EB: "/data4/chenghan/external/MergedID/Output_Merged1GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EB/XGB/XGB_modelXGB.txt"
  #   M1EE: "/data4/chenghan/external/MergedID/Output_Merged1GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EE/XGB/XGB_modelXGB.txt"
  # mergedID_wp:
  #   M2EB: 0.4283
  #   M2EE: 0.4479
  #   M1EB: 0.4390
  #   M1EE: 0.4381

  HggPhoID_model:
    EB: "../external/tmva-to-xgboost/HggPhoID/PhoID_barrel_UL2017_GJetMC_SATrain_nTree2k_LR_0p1_13052020_BDTG.weights.json"
    EE: "../external/tmva-to-xgboost/HggPhoID/PhoID_endcap_UL2017_GJetMC_SATrain_nTree2k_LR_0p1_13052020_BDTG.weights.json"
    
  # showershape_corr: # TMVA::Reader with mutex to ensure thread safty
  #   doCorr: false
  #   phoR9:
  #     EB: "/data4/chenghan/external/tmvaWeightFiles/2017/weights_finalRegressor_EB_r9.xml"
  #     EE: "/data4/chenghan/external/tmvaWeightFiles/2017/weights_finalRegressor_EE_r9.xml"

  # pileup_rewei: # PUWeightCalculator
  #   nominal: "/data4/cmkuo/tools/pileup/UL2017/PUreweight/PUreweight_13TeV_2017_GoldenJSON_69200nb.root"
  #   up: "/data4/cmkuo/tools/pileup/UL2017/PUreweight/PUreweight_13TeV_2017_GoldenJSON_72383nb.root"
  #   down: "/data4/cmkuo/tools/pileup/UL2017/PUreweight/PUreweight_13TeV_2017_GoldenJSON_66016nb.root"

  # energy_correction: # MergedEnCorrector and XGBReader (xgboost/c_api.h)
  #   energy_reg:
  #     - "/data4/chenghan/external/RegressionV3/MergedEn_Regression_XGB_EB.txt"
  #     - "/data4/chenghan/external/RegressionV3/MergedEn_Regression_XGB_EE.txt"
  #   conv_scale: # Obsolete
  #     - "/data4/chenghan/external/correction/EnConvCorr_combined_EB.root"
  #     - "/data4/chenghan/external/correction/EnConvCorr_combined_EE.root"
  #   resi_scale: # Obsolete
  #     - "/data4/chenghan/external/correction/EnScaleCorr_combined_EB_final.root"
  #     - "/data4/chenghan/external/correction/EnScaleCorr_combined_EE_final.root"
  #   resi_smear: # Obsolete
  #     - "/data4/chenghan/external/correction/EnSmearCorr_combined_EB_final.root"
  #     - "/data4/chenghan/external/correction/EnSmearCorr_combined_EE_final.root"

  # https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018
  # https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/Systematics/python/flashggDiPhotonSystematics2017_Legacy_cfi.py#L14-L24
  # scale_factors: # WeightHandler
  #   RECOEle:
  #     file: "/data4/chenghan/external/ScaleFactor/RECOEle/egammaEffi_ptAbove20.txt_EGM2D_UL2017.root"
  #     hist: "EGamma_SF2D"
  #   Fall17EleID:
  #     file: "/data4/chenghan/external/ScaleFactor/Fall17EleID/egammaEffi.txt_EGM2D_MVA90iso_UL17.root"
  #     hist: "EGamma_SF2D"
  #   Fall17PhoID:
  #     file: "/data4/chenghan/external/ScaleFactor/Fall17PhoID/egammaEffi.txt_EGM2D_PHO_MVA90_UL17.root"
  #     hist: "EGamma_SF2D"
  #   CSEV:
  #     file: "/data4/chenghan/external/ScaleFactor/CSEV/CSEV_SummaryPlot_UL17.root"
  #     hist: "MVAID/SF_CSEV_MVAID"
  #   HggPresel:
  #     absEta: [0.0, 1.5, 6]
  #     fullR9: [[0.0, 0.85, 999.], [0.0, 0.9, 999.]]
  #     values: [[0.9961, 0.9981], [1.0054 , 1.0061]]
  #     uncert: [[0.0307, 0.0057], [0.0129, 0.0018]]
