era: "UL2018"
isMC: true
luminosity: 59.82
threads: 30

# configuration for runAnalysis.cpp
############################################################################################################
#! NOTE: number of "ntuple_path",  "skimTree_path",  "miniTree_path", and "cross_section" should be the same.
ntuple_path:
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_m125/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_VBF_m125/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_WH_m125/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_ZH_m125/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_ttH_m125/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_bbH_m125/*.root"

  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_m120/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_VBF_m120/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_WH_m120/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_ZH_m120/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_ttH_m120/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_bbH_m120/*.root"

  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_m130/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_VBF_m130/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_WH_m130/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_ZH_m130/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_ttH_m130/*.root"
  - "/data5/ggNtuples/V10_06_30_02/job_UL18_Dalitz_eeg_bbH_m130/*.root"

# skimTree_path:
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_m125.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_VBF_m125.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_WH_m125.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_ZH_m125.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_ttH_m125.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_bbH_m125.root"

#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_m120.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_VBF_m120.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_WH_m120.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_ZH_m120.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_ttH_m120.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_bbH_m120.root"

#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_m130.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_VBF_m130.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_WH_m130.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_ZH_m130.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_ttH_m130.root"
#   - "/data4/chenghan/electron/skimTree/job_UL18_Dalitz_eeg_bbH_m130.root"

miniTree_path:
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ggF_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_VBF_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_WH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ZH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ttH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_bbH_eeg_125_UL2018.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ggF_eeg_120_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_VBF_eeg_120_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_WH_eeg_120_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ZH_eeg_120_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ttH_eeg_120_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_bbH_eeg_120_UL2018.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ggF_eeg_130_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_VBF_eeg_130_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_WH_eeg_130_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ZH_eeg_130_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ttH_eeg_130_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_bbH_eeg_130_UL2018.root"

# SM Higgs XS: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageAt13TeV
# Dalitz branching fraction: https://twiki.cern.ch/twiki/bin/viewauth/CMS/HiggsDalitz#Analyses_of_Run_2_at_13_TeV
cross_section:
  - 3.9301220  # (48.58  * 1000) * 8.09E-5
  - 0.30596380 # (3.782  * 1000) * 8.09E-5
  - 0.11107570 # (1.373  * 1000) * 8.09E-5
  - 0.07150751 # (0.8839 * 1000) * 8.09E-5
  - 0.04102439 # (0.5071 * 1000) * 8.09E-5
  - 0.03947920 # (0.4880 * 1000) * 8.09E-5

  - 4.1097140  # (52.22  * 1000) * 7.87E-5
  - 0.30968450 # (3.935  * 1000) * 7.87E-5
  - 0.12316550 # (1.565  * 1000) * 7.87E-5
  - 0.07821993 # (0.9939 * 1000) * 7.87E-5
  - 0.04483539 # (0.5697 * 1000) * 7.87E-5
  - 0.04355258 # (0.5534 * 1000) * 7.87E-5

  - 3.6338620  # (45.31  * 1000) * 8.02E-5
  - 0.29168740 # (3.637  * 1000) * 8.02E-5
  - 0.09696180 # (1.209  * 1000) * 8.02E-5
  - 0.06334998 # (0.7899 * 1000) * 8.02E-5
  - 0.03640278 # (0.4539 * 1000) * 8.02E-5
  - 0.03451808 # (0.4304 * 1000) * 8.02E-5

# https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#Applying_the_Energy_Scale_and_sm
# "PhiUp" and "PhiDown" are currently identical so only "RhoUp", "RhoDown" and "PhiUp" are needed for smearing
# Applying the systematic variations only to the MC
# comment the variation to skip the systematic variations
variation:
  - "PhoNoR9Corr"
  - "PhoScaleStatUp"
  - "PhoScaleSystUp"
  - "PhoScaleGainUp"
  - "PhoScaleStatDo"
  - "PhoScaleSystDo"
  - "PhoScaleGainDo"
  - "PhoSigmaPhiUp"
  - "PhoSigmaRhoUp"
  - "PhoSigmaRhoDo"
  - "EleScaleStatUp"
  - "EleScaleSystUp"
  - "EleScaleGainUp"
  - "EleScaleStatDo"
  - "EleScaleSystDo"
  - "EleScaleGainDo"
  - "EleSigmaPhiUp"
  - "EleSigmaRhoUp"
  - "EleSigmaRhoDo"

external_files:
  # mergedID_model: # XGBReader (xgboost/c_api.h)
  #   M2EB: "/data4/chenghan/external/MergedID/Output_Merged2GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EB/XGB/XGB_modelXGB.txt"
  #   M2EE: "/data4/chenghan/external/MergedID/Output_Merged2GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EE/XGB/XGB_modelXGB.txt"
  #   M1EB: "/data4/chenghan/external/MergedID/Output_Merged1GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EB/XGB/XGB_modelXGB.txt"
  #   M1EE: "/data4/chenghan/external/MergedID/Output_Merged1GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EE/XGB/XGB_modelXGB.txt"
  # mergedID_wp:
  #   M2EB: 0.4283
  #   M2EE: 0.4479
  #   M1EB: 0.4390
  #   M1EE: 0.4381

  HggPhoID_model: # XGBReader (xgboost/c_api.h)
    EB: "../external/tmva-to-xgboost/HggPhoID/PhoID_barrel_UL18_GJetMC_SATrain_BDTG_nTree2k_BDTG.weights.json"
    EE: "../external/tmva-to-xgboost/HggPhoID/PhoID_endcap_UL18_GJetMC_SATrain_BDTG_nTree2k_BDTG.weights.json"

  pileup_rewei: # PUWeightCalculator
    nominal:  "/data4/cmkuo/tools/pileup/UL2018/PUreweight/PUreweight_13TeV_2018_GoldenJSON_69200nb.root"
    up:       "/data4/cmkuo/tools/pileup/UL2018/PUreweight/PUreweight_13TeV_2018_GoldenJSON_72383nb.root"
    down:     "/data4/cmkuo/tools/pileup/UL2018/PUreweight/PUreweight_13TeV_2018_GoldenJSON_66016nb.root"

  # https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018
  # https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/Systematics/python/flashggDiPhotonSystematics2017_Legacy_cfi.py#L14-L24
  scale_factors: # WeightHandler
    RecoEleGt20: # greater than 20
      file: "/data4/chenghan/external/ScaleFactor/RecoEleGt20/egammaEffi_ptAbove20.txt_EGM2D_UL2018.root"
      hist: "EGamma_SF2D"
    RecoEleLt20: # less than 20
      file: "/data4/chenghan/external/ScaleFactor/RecoEleLt20/egammaEffi_ptBelow20.txt_EGM2D_UL2018.root"
      hist: "EGamma_SF2D"
    Fall17EleID:
      file: "/data4/chenghan/external/ScaleFactor/Fall17EleID/egammaEffi.txt_Ele_wp90iso_EGM2D.root"
      hist: "EGamma_SF2D"
    SingleEleHLT:
      file: "/data4/chenghan/external/ScaleFactor/SingleEleTrig/singleElTrigEff_2018.root"
      hist: "EGamma_SF2D"
    HggPreselForPho:
      absEta: [0.0, 1.5, 6]
      fullR9: [[0.0, 0.85, 999.], [0.0, 0.9, 999.]]
      values: [[1.0017, 0.9973], [1.0030 , 1.0031]]
      uncert: [[0.0237, 0.0067], [0.0210, 0.0024]]
    HggPhoCSEV:
      absEta: [0.0, 1.5, 6]
      fullR9: [[0.0, 0.85, 999.], [0.0, 0.9, 999.]]
      values: [[0.9830, 0.9939], [0.9603 , 0.9754]]
      uncert: [[0.0021, 0.0005], [0.0077, 0.0017]]
    HggPhoID:
      absEta: [0.0, 1.5, 6]
      fullR9: [[0.0, 0.85, 999.], [0.0, 0.9, 999.]]
      values: [[1.0022, 1.0005], [1.0058 , 1.0013]]
      uncert: [[0.0012, 0.0033], [0.0020, 0.0028]]