era: "UL2016preVFP"
isMC: true
luminosity: 19.52
threads: 30

# configuration for runAnalysis.cpp
############################################################################################################
#! NOTE: number of "datasets_path", "cross_section", and "miniTree_path" should be the same.
datasets_path:
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_m125_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_VBF_m125_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_WH_m125_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_ZH_m125_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_ttH_m125_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_bbH_m125_preVFP.root"

  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_m120_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_VBF_m120_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_WH_m120_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_ZH_m120_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_ttH_m120_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_bbH_m120_preVFP.root"

  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_m130_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_VBF_m130_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_WH_m130_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_ZH_m130_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_ttH_m130_preVFP.root"
  - "/data4/chenghan/electron/skimTree/job_UL16_Dalitz_eeg_bbH_m130_preVFP.root"

# SM Higgs XS: https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageAt13TeV
cross_section:
  - 3.9301220  # (48.58  * 1000) * 8.09E-5
  - 0.30596380 # (3.782  * 1000) * 8.09E-5
  - 0.11107570 # (1.373  * 1000) * 8.09E-5
  - 0.07150751 # (0.8839 * 1000) * 8.09E-5
  - 0.04102439 # (0.5071 * 1000) * 8.09E-5
  - 0.03947920 # (0.4880 * 1000) * 8.09E-5

  - 4.1097140  # (52.22  * 1000) * 7.87E-5
  - 0.30968450 # (3.935  * 1000) * 7.87E-5
  - 0.12316550 # (1.565  * 1000) * 7.87E-5
  - 0.07821993 # (0.9939 * 1000) * 7.87E-5
  - 0.04483539 # (0.5697 * 1000) * 7.87E-5
  - 0.04355258 # (0.5534 * 1000) * 7.87E-5

  - 3.6338620  # (45.31  * 1000) * 8.02E-5
  - 0.29168740 # (3.637  * 1000) * 8.02E-5
  - 0.09696180 # (1.209  * 1000) * 8.02E-5
  - 0.06334998 # (0.7899 * 1000) * 8.02E-5
  - 0.03640278 # (0.4539 * 1000) * 8.02E-5
  - 0.03451808 # (0.4304 * 1000) * 8.02E-5

miniTree_path:
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ggF_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_VBF_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_WH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ZH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ttH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_bbH_eeg_125_UL2016preVFP.root"

  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ggF_eeg_120_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_VBF_eeg_120_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_WH_eeg_120_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ZH_eeg_120_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ttH_eeg_120_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_bbH_eeg_120_UL2016preVFP.root"

  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ggF_eeg_130_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_VBF_eeg_130_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_WH_eeg_130_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ZH_eeg_130_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_ttH_eeg_130_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree/UL2016preVFP/miniTree_HDalitz_bbH_eeg_130_UL2016preVFP.root"

# https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#Applying_the_Energy_Scale_and_sm
# "PhiUp" and "PhiDown" are currently identical so only "RhoUp", "RhoDown" and "PhiUp" are needed for smearing
# Applying the systematic variations only to the MC
# comment the variation to skip the systematic variations
# jet energy variations are only needed for HVBF and LVBF categories
variation:
  - "JERUp"
  - "JERDo"
  - "JECUp"
  - "JECDo"
  - "PhoScaleStatUp"
  - "PhoScaleSystUp"
  - "PhoScaleGainUp"
  - "PhoScaleStatDo"
  - "PhoScaleSystDo"
  - "PhoScaleGainDo"
  - "PhoSigmaPhiUp"
  - "PhoSigmaRhoUp"
  - "PhoSigmaRhoDo"
  - "EleScaleStatUp"
  - "EleScaleSystUp"
  - "EleScaleGainUp"
  - "EleScaleStatDo"
  - "EleScaleSystDo"
  - "EleScaleGainDo"
  - "EleSigmaPhiUp"
  - "EleSigmaRhoUp"
  - "EleSigmaRhoDo"
  - "EleHDALScaleUp"
  - "EleHDALScaleDo"
  - "EleHDALSmearUp"
  - "EleHDALSmearDo"

external_files:
  mergedID_model: # XGBReader (xgboost/c_api.h)
    M2EB: "/data4/chenghan/external/MergedID/Output_Merged2GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EB/XGB/XGB_modelXGB.txt"
    M2EE: "/data4/chenghan/external/MergedID/Output_Merged2GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EE/XGB/XGB_modelXGB.txt"
    M1EB: "/data4/chenghan/external/MergedID/Output_Merged1GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EB/XGB/XGB_modelXGB.txt"
    M1EE: "/data4/chenghan/external/MergedID/Output_Merged1GsfID_hyperTune_FullRun2ULWPPtWeiFinal_EE/XGB/XGB_modelXGB.txt"
  mergedID_wp:
    M2EB: 0.4283
    M2EE: 0.4479
    M1EB: 0.4390
    M1EE: 0.4381

  showershape_corr: # TMVA::Reader with mutex to ensure thread safty
    doCorr: false
    phoR9:
      EB: "/data4/chenghan/external/tmvaWeightFiles/2017/weights_finalRegressor_EB_r9.xml"
      EE: "/data4/chenghan/external/tmvaWeightFiles/2017/weights_finalRegressor_EE_r9.xml"

  pileup_rewei: # PUWeightCalculator
    nominal: "/data4/cmkuo/tools/pileup/UL2016preVFP/PUreweight/PUreweight_13TeV_2016preVFP_GoldenJSON_69200nb.root"
    up: "/data4/cmkuo/tools/pileup/UL2016preVFP/PUreweight/PUreweight_13TeV_2016preVFP_GoldenJSON_72383nb.root"
    down: "/data4/cmkuo/tools/pileup/UL2016preVFP/PUreweight/PUreweight_13TeV_2016preVFP_GoldenJSON_66016nb.root"

  energy_correction: # EnCalibrater
    conv_scale:
      - "/data4/chenghan/external/correction/EnConvCorr_combined_EB.root"
      - "/data4/chenghan/external/correction/EnConvCorr_combined_EE.root"
    resi_scale:
      - "/data4/chenghan/external/correction/EnScaleCorr_combined_EB_final.root"
      - "/data4/chenghan/external/correction/EnScaleCorr_combined_EE_final.root"
    resi_smear:
      - "/data4/chenghan/external/correction/EnSmearCorr_combined_EB_final.root"
      - "/data4/chenghan/external/correction/EnSmearCorr_combined_EE_final.root"

  # https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018
  # https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/Systematics/python/flashggDiPhotonSystematics2017_Legacy_cfi.py#L14-L24
  # Hgg preselection SFs for UL2016preVFP are temporarily assigned as UL2017 ones
  scale_factors: # WeightHandler
    RECOEle:
      file: "/data4/chenghan/external/ScaleFactor/RECOEle/egammaEffi_ptAbove20.txt_EGM2D_UL2016preVFP.root"
      hist: "EGamma_SF2D"
    Fall17EleID:
      file: "/data4/chenghan/external/ScaleFactor/Fall17EleID/egammaEffi.txt_Ele_wp90iso_preVFP_EGM2D.root"
      hist: "EGamma_SF2D"
    Fall17PhoID:
      file: "/data4/chenghan/external/ScaleFactor/Fall17PhoID/egammaEffi.txt_EGM2D_Pho_wp90_UL16.root"
      hist: "EGamma_SF2D"
    CSEV:
      file: "/data4/chenghan/external/ScaleFactor/CSEV/CSEV_SummaryPlot_UL16_preVFP.root"
      hist: "MVAID/SF_CSEV_MVAID"
    HggPresel:
      absEta: [0.0, 1.5, 6]
      fullR9: [[0.0, 0.85, 999.], [0.0, 0.9, 999.]]
      values: [[0.9961, 0.9981], [1.0054 , 1.0061]]
      uncert: [[0.0307, 0.0057], [0.0129, 0.0018]]
