# configuration for drawKinematic.cpp and runSignificance .cpp
############################################################################################################
mcTree_path:
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_HDalitz_ggF_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_HDalitz_VBF_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_HDalitz_WH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_HDalitz_ZH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_HDalitz_ttH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_HDalitz_bbH_eeg_125_UL2016preVFP.root"

  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_HDalitz_ggF_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_HDalitz_VBF_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_HDalitz_WH_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_HDalitz_ZH_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_HDalitz_ttH_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_HDalitz_bbH_eeg_125_UL2016postVFP.root"

  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_HDalitz_ggF_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_HDalitz_VBF_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_HDalitz_WH_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_HDalitz_ZH_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_HDalitz_ttH_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_HDalitz_bbH_eeg_125_UL2017.root"

  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_HDalitz_ggF_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_HDalitz_VBF_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_HDalitz_WH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_HDalitz_ZH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_HDalitz_ttH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_HDalitz_bbH_eeg_125_UL2018.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_HDalitz_ggF_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_HDalitz_VBF_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_HDalitz_WH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_HDalitz_ZH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_HDalitz_ttH_eeg_125_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_HDalitz_bbH_eeg_125_UL2016preVFP.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_HDalitz_ggF_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_HDalitz_VBF_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_HDalitz_WH_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_HDalitz_ZH_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_HDalitz_ttH_eeg_125_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_HDalitz_bbH_eeg_125_UL2016postVFP.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_HDalitz_ggF_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_HDalitz_VBF_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_HDalitz_WH_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_HDalitz_ZH_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_HDalitz_ttH_eeg_125_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_HDalitz_bbH_eeg_125_UL2017.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ggF_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_VBF_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_WH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ZH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_ttH_eeg_125_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_HDalitz_bbH_eeg_125_UL2018.root"



dataTree_path:
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_DoubleEG_Run2016B_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_DoubleEG_Run2016C_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_DoubleEG_Run2016D_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_DoubleEG_Run2016E_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016preVFP/miniTree_DoubleEG_Run2016F1_UL2016preVFP.root"

  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_DoubleEG_Run2016F2_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_DoubleEG_Run2016G_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2016postVFP/miniTree_DoubleEG_Run2016H_UL2016postVFP.root"

  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_DoubleEG_Run2017B_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_DoubleEG_Run2017C_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_DoubleEG_Run2017D_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_DoubleEG_Run2017E_UL2017.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2017/miniTree_DoubleEG_Run2017F_UL2017.root"

  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_EGamma_Run2018A_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_EGamma_Run2018B_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_EGamma_Run2018C_UL2018.root"
  - "/data4/chenghan/electron/miniTree_merged/UL2018/miniTree_EGamma_Run2018D_UL2018.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_SingleEle_Run2016B_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_SingleEle_Run2016C_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_SingleEle_Run2016D_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_SingleEle_Run2016E_UL2016preVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016preVFP/miniTree_SingleEle_Run2016F1_UL2016preVFP.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_SingleEle_Run2016F2_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_SingleEle_Run2016G_UL2016postVFP.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2016postVFP/miniTree_SingleEle_Run2016H_UL2016postVFP.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017B_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017C_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017D_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017E_UL2017.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2017/miniTree_SingleEle_Run2017F_UL2017.root"

  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_EGamma_Run2018A_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_EGamma_Run2018B_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_EGamma_Run2018C_UL2018.root"
  - "/data4/chenghan/electron/miniTree_resolved/UL2018/miniTree_EGamma_Run2018D_UL2018.root"

cms_lumi:
  lumi_text: "138 fb^{-1}"
  year: 2017
  extra_text: "Preliminary"
  proc_text:  "H #rightarrow #gamma* #gamma #rightarrow ee#gamma"

AMS_file: "../ams/AMS_fullRun2_ResolvedMerged.txt"
significance:
  mass_range: [110, 170]
  mass_column: "CMS_higgs_mass"
  weight_column: "weight"
  category: # category name and the corresponding selection in minitree
    Merged-2Gsf-VBF:    "category == 1"
    Merged-2Gsf-Bst:    "category == 2"
    Merged-2Gsf-EBHR9:  "category == 3"
    Merged-2Gsf-EBLR9:  "category == 4"
    Merged-2Gsf-EE:     "category == 5"
    Resolved:           "category == 6"
    # Resolved-EBHR9:     "category == 6"
    # Resolved-EBLR9:     "category == 7"
    # Resolved-EE:        "category == 8"

    # Merged-1Gsf-HVBF:   "category == 7"
    # Merged-1Gsf-LVBF:   "category == 8"
    # Merged-1Gsf-Bst:    "category == 9"
    # Merged-1Gsf-EBHR9:  "category == 10"
    # Merged-1Gsf-EBLR9:  "category == 11"
    # Merged-1Gsf-EE:     "category == 12"
    # Resolved:           "category == 13"